export * from "./categoryMoviesPage/CategoryMovies.tsx"
export * from "./favoritesPage/Favorites.tsx"
export * from "./filteredMoviesPage/FilteredMovies.tsx"
export * from "./main/Main.tsx"
export * from "./searchPage/Search.tsx"
